name: "Release"

on: # @see https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
  push:
    tags:
      - "*"

jobs:
  build: # job id, can be any string
    # Job name is Build And Publish
    name: Build
    # This job runs on Linux
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout And Create Tag
        uses: actions/checkout@v2
        env:
          TAG_REF: ${{ github.ref }}
        run: |
          TAG_NAME=${TAG_REF/*\/} ;
          MAJOR_TAG_NAME=${TAG_NAME/.*} ;
          if [[ "$MAJOR_TAG_NAME" != "$TAG_NAME" ]]; then
            git config user.name github-actions ;
            git config user.email github-actions@github.com ;
            git tag -d $MAJOR_TAG_NAME || true ;
            git push -f --tags ;
          fi