name: "Create Release Major Tag"

on: # @see https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events
  push:
    tags:
      - "*"

jobs:
  create_Release_major_tag: # job id, can be any string
    # Job name is Build And Publish
    name: "Create Release Major Tag"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout And Create Tag
        uses: actions/checkout@v2
        env:
          TAG_REF: ${{ github.ref }}
        if: ${{ startsWith(github.ref, 'refs/tags/') && contains(github.ref, '.') }}
        run: |
          TAG_NAME=${TAG_REF/*\/} ;
          MAJOR_TAG_NAME=${TAG_NAME/.*} ;
          if [[ "$MAJOR_TAG_NAME" != "$TAG_NAME" ]]; then
            git config user.name github-actions ;
            git config user.email github-actions@github.com ;
            git tag -d $MAJOR_TAG_NAME || true ;
            git push -f --tags ;
          fi